spring:
  jta:
    atomikos:
      properties:
        max-timeout: 10000
        enable-logging: false
      datasource:
        order:
          unique-resource-name: orderdb
          xa-data-source-class-name: org.postgresql.xa.PGXADataSource
          xa-properties:
            url: jdbc:postgresql://localhost:5432/orderdb
            user: orderuser
            password: orderpassword
        stock:
          unique-resource-name: stockdb
          xa-data-source-class-name: org.postgresql.xa.PGXADataSource
          xa-properties:
            url: jdbc:postgresql://localhost:5433/stockdb
            user: stockuser
            password: stockpassword

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true

atomikos:
  properties:
    max-timeout: 10000
