CREATE TABLE IF NOT EXISTS orders (
  id SERIAL PRIMARY KEY,
  order_name VARCHAR(255) NOT NULL,
  order_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

ALTER SYSTEM SET max_prepared_transactions = 100;
